LEFT = (0, -1)
RIGHT = (0, 1)
UP = (-1, 0)
DOWN = (1, 0)
PICKUP = (0, 0)

ACTION_INDEX ={}
ACTION_INDEX[LEFT] = 0
ACTION_INDEX[RIGHT] = 1
ACTION_INDEX[UP] = 2
ACTION_INDEX[DOWN] = 3
ACTION_INDEX[PICKUP] = 4

INDEX_ACTION = {}
INDEX_ACTION[0] = LEFT
INDEX_ACTION[1] = RIGHT
INDEX_ACTION[2] = UP
INDEX_ACTION[3] = DOWN
INDEX_ACTION[5] = PICKUP